# Generated by Django 5.2.2 on 2025-06-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=50)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
                ('senha_usuario', models.CharField(max_length=255)),
                ('data_criacao_usuario', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
